version: "3.4"

networks:
  backend:
    driver: bridge
  frontend:

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:11.12
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    env_file:
      - ./.docker/postgres/database.env
    ports:
      - "15432:5432"
    networks:
      - backend
      - frontend
    environment:
      POSTGRES_DB: livraria